-- MySQL Script generated by MySQL Workbench
-- Tue Jun 12 03:45:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clinica_v1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinica_v1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_v1` DEFAULT CHARACTER SET utf8 ;
USE `clinica_v1` ;

-- -----------------------------------------------------
-- Table `clinica_v1`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`pessoa` (
  `pessoaCodigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `dataNascimento` DATE NULL,
  `sexo` CHAR(1) NULL,
  `profissao` VARCHAR(45) NULL,
  `telefone` VARCHAR(11) NULL,
  `celular` VARCHAR(11) NULL,
  `logradouro` VARCHAR(200) NULL,
  `numeroResidencia` VARCHAR(10) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `uf` VARCHAR(2) NULL,
  `cep` VARCHAR(9) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`pessoaCodigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`cargo` (
  `cargoCodigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cargoCodigo`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`funcionario` (
  `funcionarioCodigo` INT NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cargoCodigo` INT NOT NULL,
  PRIMARY KEY (`funcionarioCodigo`),
  INDEX `fk_funcionario_pessoa_idx` (`funcionarioCodigo` ASC),
  INDEX `fk_funcionario_cargos1_idx` (`cargoCodigo` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_funcionario_pessoa`
    FOREIGN KEY (`funcionarioCodigo`)
    REFERENCES `clinica_v1`.`pessoa` (`pessoaCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_cargos1`
    FOREIGN KEY (`cargoCodigo`)
    REFERENCES `clinica_v1`.`cargo` (`cargoCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`especializacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`especializacao` (
  `especializacaoCodigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`especializacaoCodigo`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`conselhoRegional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`conselhoRegional` (
  `conselhoCodigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`conselhoCodigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`profissional` (
  `profissionalCodigo` INT NOT NULL,
  `conselhoCodigo` INT NOT NULL,
  `numConselho` INT NOT NULL,
  `ufConselho` VARCHAR(2) NOT NULL,
  `especializacaoCodigo` INT NOT NULL,
  PRIMARY KEY (`profissionalCodigo`),
  UNIQUE INDEX `numConselho_UNIQUE` (`numConselho` ASC),
  INDEX `fk_profissionais_especializacoes1_idx` (`especializacaoCodigo` ASC),
  INDEX `fk_profissionais_pessoas1_idx` (`profissionalCodigo` ASC),
  INDEX `fk_profissionais_conselhosRegionais1_idx` (`conselhoCodigo` ASC),
  CONSTRAINT `fk_profissionais_especializacoes1`
    FOREIGN KEY (`especializacaoCodigo`)
    REFERENCES `clinica_v1`.`especializacao` (`especializacaoCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissionais_pessoas1`
    FOREIGN KEY (`profissionalCodigo`)
    REFERENCES `clinica_v1`.`pessoa` (`pessoaCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissionais_conselhosRegionais1`
    FOREIGN KEY (`conselhoCodigo`)
    REFERENCES `clinica_v1`.`conselhoRegional` (`conselhoCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`paciente` (
  `pacienteCodigo` INT NOT NULL,
  `altura` DECIMAL(3,2) NULL,
  `peso` DECIMAL(6,3) NULL,
  `cirurgia` VARCHAR(500) NULL,
  `gestacao` VARCHAR(500) NULL,
  `alergia` VARCHAR(500) NULL,
  `pressaoArterial` VARCHAR(500) NULL,
  `tipoSanguineo` VARCHAR(3) NULL,
  `deficiencia` VARCHAR(500) NULL,
  `dum` DATE NULL,
  `observacao` VARCHAR(500) NULL,
  PRIMARY KEY (`pacienteCodigo`),
  CONSTRAINT `fk_paciente_pessoas1`
    FOREIGN KEY (`pacienteCodigo`)
    REFERENCES `clinica_v1`.`pessoa` (`pessoaCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`convenio` (
  `convenioCodigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `razaoSocial` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(200) NULL,
  `numeroResidencia` VARCHAR(10) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(200) NULL,
  `uf` VARCHAR(2) NULL,
  `cep` VARCHAR(9) NULL,
  `email` VARCHAR(200) NULL,
  PRIMARY KEY (`convenioCodigo`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  UNIQUE INDEX `razaoSocial_UNIQUE` (`razaoSocial` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`consulta` (
  `consultaCodigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`consultaCodigo`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`formaPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`formaPagamento` (
  `formaPagCodigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`formaPagCodigo`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`ConsultaPorConvenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`ConsultaPorConvenio` (
  `convenioCodigo` INT NOT NULL,
  `consultaCodigo` INT NOT NULL,
  `valor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`convenioCodigo`, `consultaCodigo`),
  INDEX `fk_procedimentos_has_convenios_convenios1_idx` (`convenioCodigo` ASC),
  INDEX `fk_procedimentos_has_convenios_procedimentos1_idx` (`consultaCodigo` ASC),
  CONSTRAINT `fk_procedimentos_has_convenios_procedimentos1`
    FOREIGN KEY (`consultaCodigo`)
    REFERENCES `clinica_v1`.`consulta` (`consultaCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_procedimentos_has_convenios_convenios1`
    FOREIGN KEY (`convenioCodigo`)
    REFERENCES `clinica_v1`.`convenio` (`convenioCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`agenda` (
  `agendamentoCodigo` INT NOT NULL AUTO_INCREMENT,
  `profissionalCodigo` INT NOT NULL,
  `dataAgendamento` DATETIME NOT NULL,
  `pacienteCodigo` INT NOT NULL,
  `convenioCodigo` INT NOT NULL,
  `consultaCodigo` INT NOT NULL,
  `agendadoPor` INT NOT NULL,
  `agendadoEm` DATETIME NOT NULL,
  `observacao` VARCHAR(200) NULL,
  PRIMARY KEY (`agendamentoCodigo`),
  INDEX `fk_agenda_pacientes1_idx` (`pacienteCodigo` ASC),
  INDEX `fk_agenda_funcionarios1_idx` (`agendadoPor` ASC),
  INDEX `fk_agenda_procedimentos_has_convenios1_idx` (`convenioCodigo` ASC, `consultaCodigo` ASC),
  INDEX `fk_agenda_profissionais1_idx` (`profissionalCodigo` ASC),
  CONSTRAINT `fk_agenda_pacientes1`
    FOREIGN KEY (`pacienteCodigo`)
    REFERENCES `clinica_v1`.`paciente` (`pacienteCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_funcionarios1`
    FOREIGN KEY (`agendadoPor`)
    REFERENCES `clinica_v1`.`funcionario` (`funcionarioCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_procedimentos_has_convenios1`
    FOREIGN KEY (`convenioCodigo` , `consultaCodigo`)
    REFERENCES `clinica_v1`.`ConsultaPorConvenio` (`convenioCodigo` , `consultaCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_profissionais1`
    FOREIGN KEY (`profissionalCodigo`)
    REFERENCES `clinica_v1`.`profissional` (`profissionalCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`faturamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`faturamento` (
  `faturamentoCodigo` INT NOT NULL AUTO_INCREMENT,
  `agendamentoCodigo` INT NOT NULL,
  `porcentagemDesconto` DECIMAL(5,2) NULL,
  `valorTotal` DOUBLE NOT NULL,
  `formaPagCodigo` INT NOT NULL,
  `faturadoPor` INT NOT NULL,
  `dataFaturamento` DATETIME NOT NULL,
  PRIMARY KEY (`faturamentoCodigo`),
  INDEX `fk_faturamento_agenda1_idx` (`agendamentoCodigo` ASC),
  INDEX `fk_faturamento_formasPagamento1_idx` (`formaPagCodigo` ASC),
  INDEX `fk_faturamento_funcionarios1_idx` (`faturadoPor` ASC),
  CONSTRAINT `fk_faturamento_agenda1`
    FOREIGN KEY (`agendamentoCodigo`)
    REFERENCES `clinica_v1`.`agenda` (`agendamentoCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_faturamento_formasPagamento1`
    FOREIGN KEY (`formaPagCodigo`)
    REFERENCES `clinica_v1`.`formaPagamento` (`formaPagCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_faturamento_funcionarios1`
    FOREIGN KEY (`faturadoPor`)
    REFERENCES `clinica_v1`.`funcionario` (`funcionarioCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`laudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`laudo` (
  `laudoCodigo` INT NOT NULL AUTO_INCREMENT,
  `faturamentoCodigo` INT NOT NULL,
  `laudo` VARCHAR(2000) NULL,
  PRIMARY KEY (`laudoCodigo`, `faturamentoCodigo`),
  INDEX `fk_laudos_faturamento1_idx` (`faturamentoCodigo` ASC),
  CONSTRAINT `fk_laudos_faturamento1`
    FOREIGN KEY (`faturamentoCodigo`)
    REFERENCES `clinica_v1`.`faturamento` (`faturamentoCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_v1`.`horarioAgenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_v1`.`horarioAgenda` (
  `profissionalCodigo` INT NOT NULL,
  `horario` VARCHAR(5) NOT NULL,
  INDEX `fk_horariosAgenda_profissionais1_idx` (`profissionalCodigo` ASC),
  PRIMARY KEY (`profissionalCodigo`, `horario`),
  CONSTRAINT `fk_horariosAgenda_profissionais1`
    FOREIGN KEY (`profissionalCodigo`)
    REFERENCES `clinica_v1`.`profissional` (`profissionalCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
