/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.faturamento;

import model.bean.AgendaBean;
import model.bean.ConsultaPorConvenioBean;
import model.bean.FaturamentoBean;
import model.bean.FormaPagamentoBean;
import controller.AgendaController;
import controller.ConsultaPorConvenioController;
import controller.FaturamentoController;
import dao.AgendaDAO;
import dao.ConsultaPorConvenioDAO;
import java.util.Date;
import javax.swing.JOptionPane;
import model.combobox.ForPagamentoComboBoxModel;
import util.MaskFormatTextUtil;
import util.SessaoUtil;

/**
 *
 * @author vande
 */
public class FaturarAgendamentoView extends javax.swing.JDialog {

    private static FaturamentoBean faturamento = new FaturamentoBean();
    private ForPagamentoComboBoxModel cbmForPagamento = new ForPagamentoComboBoxModel();

    /**
     * Creates new form FaturarAgendamento
     */
    public FaturarAgendamentoView(java.awt.Frame parent, boolean modal, AgendaBean agendamento) {
        super(parent, modal);
        initComponents();
        faturamento.setAgenda(AgendaController.searchAgendamento(agendamento));
        setForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlProfissional = new javax.swing.JLabel();
        jlDataConsulta = new javax.swing.JLabel();
        jlPaciente = new javax.swing.JLabel();
        jlConvenio = new javax.swing.JLabel();
        jlConsulta = new javax.swing.JLabel();
        jlAgendadoPor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtValorConsulta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcbFormaPagamento = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        btnFaturar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtDesconto = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cila's System - Faturar agendamento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("FATURAR AGENDAMENTO");

        jlProfissional.setText("Profissional realizante:");

        jlDataConsulta.setText("Data da consulta:");

        jlPaciente.setText("Nome do paciente:");

        jlConvenio.setText("Convênio:");

        jlConsulta.setText("Tipo da consulta:");

        jlAgendadoPor.setText("Agendado por:");

        jLabel8.setText("Valor da consulta:");

        txtValorConsulta.setEditable(false);

        jLabel9.setText("Forma de pagamento:");

        jcbFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFormaPagamentoActionPerformed(evt);
            }
        });

        jLabel10.setText("Desconto:");

        jLabel11.setText("Valor total:");

        txtValorTotal.setEditable(false);

        btnFaturar.setText("FATURAR AGENDAMENTO");
        btnFaturar.setEnabled(false);
        btnFaturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturarActionPerformed(evt);
            }
        });

        txtDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtDesconto.setText("0");
        txtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescontoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlPaciente)
                                    .addComponent(jlConvenio)
                                    .addComponent(jlConsulta))
                                .addGap(213, 213, 213)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlProfissional)
                                    .addComponent(jlDataConsulta)
                                    .addComponent(jlAgendadoPor)))
                            .addComponent(btnFaturar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValorConsulta, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jcbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(127, 127, 127))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPaciente)
                    .addComponent(jlProfissional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlConvenio)
                    .addComponent(jlDataConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlConsulta)
                    .addComponent(jlAgendadoPor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFaturar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ConsultaPorConvenioBean conByCon = new ConsultaPorConvenioBean();
        conByCon.setConvenio(faturamento.getAgenda().getConvenio());
        conByCon.setConsultaCodigo(faturamento.getAgenda().getConsulta().getConsultaCodigo());
        txtValorConsulta.setText(ConsultaPorConvenioController.searchValorConsulta(conByCon).getValor());
        calcValorTotal();
    }//GEN-LAST:event_formWindowOpened

    private void txtDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescontoFocusLost
        // TODO add your handling code here:
        calcValorTotal();
    }//GEN-LAST:event_txtDescontoFocusLost

    private void jcbFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFormaPagamentoActionPerformed
        // TODO add your handling code here:
        checkForm();
    }//GEN-LAST:event_jcbFormaPagamentoActionPerformed

    private void btnFaturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturarActionPerformed
        // TODO add your handling code here:
        if (checkForm()) {
            faturamento.setDataFaturamento(MaskFormatTextUtil.dataTimeUs(new Date(System.currentTimeMillis())));
            faturamento.setFaturadoPor(SessaoUtil.getFuncionario());
            faturamento.setFormaPagamento((FormaPagamentoBean) jcbFormaPagamento.getSelectedItem());
            faturamento.setPorcentagemDesconto(Integer.parseInt(txtDesconto.getText()));
            faturamento.setValorTotal(MaskFormatTextUtil.changeCommaByDot(txtValorTotal.getText()));
            FaturamentoController.createFaturamento(faturamento);
            this.setVisible(false);
        } else {
            System.err.println("DADOS INVÁLIDOS");
        }
    }//GEN-LAST:event_btnFaturarActionPerformed

    /**
     * Preenche dados no formulario de faturamento
     */
    private void setForm() {
        jlPaciente.setText("Nome do paciente: " + faturamento.getAgenda().getPaciente().getNome());
        jlConvenio.setText("Convênio: " + faturamento.getAgenda().getConvenio().getNome());
        jlConsulta.setText("Consulta: " + faturamento.getAgenda().getConsulta().getDescricao());
        jlProfissional.setText("Profissional realizante: " + faturamento.getAgenda().getProfissional().getNome());
        jlAgendadoPor.setText("Agendado por: " + faturamento.getAgenda().getAgendadoPor().getNome());
        jlDataConsulta.setText("Data da consulta: " + MaskFormatTextUtil.dataBr(faturamento.getAgenda().getDataAgendamento()));
        jcbFormaPagamento.setModel(cbmForPagamento);
    }

    /**
     * Calcular desconto e alterar valores dos campos relacionados.
     */
    private void calcValorTotal() {
        try {
            int desconto = Integer.parseInt(txtDesconto.getText());
            if (desconto <= 100 && desconto >= 0) {
                double valorConsulta = MaskFormatTextUtil.changeCommaByDot(txtValorConsulta.getText());
                double valorTotal = valorConsulta - ((valorConsulta / 100) * desconto);
                txtValorTotal.setText(MaskFormatTextUtil.changeDotByComma(String.format("%.2f", valorTotal)));
                checkForm2();
            } else {
                JOptionPane.showMessageDialog(this, "O desconto deve estar no intervalo de 0-100%.");
                resetValorTotal();
            }
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Apenas números inteiros são permitidos para o desconto.");
            resetValorTotal();
        }
    }

    /**
     * Reseta o campo de desconto e desativa o botão de faturar.
     */
    private void resetValorTotal() {
        txtDesconto.setText("0");
        btnFaturar.setEnabled(false);
    }

    /**
     * válidar formulário e caso necessário informa o user sobre o problema.
     *
     * @return
     */
    private boolean checkForm() {
        if (jcbFormaPagamento.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Informe uma forma de pagamento.");
            return false;
        }
        if (txtDesconto.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Informe um valor de desconto. Caso não haja, informe 0.");
            return false;
        }
        btnFaturar.setEnabled(true);
        return true;
    }

    /**
     * válidar formulário e libera o botão de faturar
     *
     * @return
     */
    private boolean checkForm2() {
        if (jcbFormaPagamento.getSelectedIndex() == -1) {
            return false;
        }
        if (txtDesconto.getText().equalsIgnoreCase("")) {
            return false;
        }
        btnFaturar.setEnabled(true);
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturarAgendamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturarAgendamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturarAgendamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturarAgendamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FaturarAgendamentoView dialog = new FaturarAgendamentoView(new javax.swing.JFrame(), true, faturamento.getAgenda());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFaturar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jcbFormaPagamento;
    private javax.swing.JLabel jlAgendadoPor;
    private javax.swing.JLabel jlConsulta;
    private javax.swing.JLabel jlConvenio;
    private javax.swing.JLabel jlDataConsulta;
    private javax.swing.JLabel jlPaciente;
    private javax.swing.JLabel jlProfissional;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JTextField txtValorConsulta;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables

}
