/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.configuracoes;

import model.bean.ConselhoRegionalBean;
import model.bean.EspecializacaoBean;
import model.bean.FormaPagamentoBean;
import model.bean.ProfissionalBean;
import controller.ConselhoRegionalController;
import controller.EspecializacaoController;
import controller.FormaPagamentoController;
import controller.HorarioAgendaController;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.jlist.ConselhoRegionalJListModel;
import model.jlist.EspecializacaoJListModel;
import model.jlist.FormaPagamentoJListModel;
import model.jlist.HorarioAgendaJListModel;
import model.jlist.ProfissionalJListModel;

/**
 *
 * @author vande
 */
public class ConfiguracoesView extends javax.swing.JFrame {

    private ProfissionalBean pro = null;
    private String horario;
    private String especializacao;
    private String conselhoregional;
    private String formapagamento;

    /**
     * Creates new form Configuracoes
     */
    public ConfiguracoesView() {
        initComponents();
        defListas();
        defListPro();
        redefHoras(0);
    }

    /**
     * Definir listas do frame, exceto a de profissionais pois é a única lista em
     * que podem serem inseridados novos valores fora do frame de configurações,
     * sendo assim necessário atualizada separadamnete das demais JList deste
     * frame.
     */
    private void defListas(){
        jlEspecializacoes.setModel(new EspecializacaoJListModel(""));
        jlEspecializacoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jlConRegionais.setModel(new ConselhoRegionalJListModel(""));
        jlConRegionais.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jlFormas.setModel(new FormaPagamentoJListModel(""));
        jlFormas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    /**
     * Definir a lista de profissionais separadamente, pois é a única lista em
     * que podem ser inseridados novos valores fora do frame de configurações,
     * sendo assim necessário atualizada separadamnete das demais JList deste
     * frame.
     */
    private void defListPro() {
        jlProfissionais.setModel(new ProfissionalJListModel(""));
        jlProfissionais.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * Define a lista de horas
     *
     * @param profissionalCodigo
     */
    private void redefHoras(int profissionalCodigo) {
        jlHoras.setModel(new HorarioAgendaJListModel(profissionalCodigo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpCabecalho = new javax.swing.JTabbedPane();
        jpConRegional = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblConselho = new javax.swing.JLabel();
        txtNovoConselho = new javax.swing.JTextField();
        btnCadastrarConRegional = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlConRegionais = new javax.swing.JList<>();
        btnEditarConRegional = new javax.swing.JButton();
        jpEspecialidades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEspecialidade = new javax.swing.JLabel();
        txtNomeEspecializacao = new javax.swing.JTextField();
        btnCadastrarEsp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlEspecializacoes = new javax.swing.JList<>();
        btnEditarEsp = new javax.swing.JButton();
        jpForPagamento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEditarForPag = new javax.swing.JButton();
        lblForma = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlFormas = new javax.swing.JList<>();
        txtNomeForma = new javax.swing.JTextField();
        btnCadastrarForPag = new javax.swing.JButton();
        jpHorProfissionais = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblProfissional = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlProfissionais = new javax.swing.JList<>();
        btnCadastrarHorario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlHoras = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        txtNovaHora = new javax.swing.JFormattedTextField();
        btnExcluirHorario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cila's System - Configurações");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel4.setText("GERENCIAR CONSELHOS REGIONAIS");

        lblConselho.setText("Novo conselho:");

        btnCadastrarConRegional.setText("CADASTRAR");
        btnCadastrarConRegional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarConRegionalActionPerformed(evt);
            }
        });

        jlConRegionais.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlConRegionais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConRegionaisMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jlConRegionais);

        btnEditarConRegional.setText("EDITAR");
        btnEditarConRegional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarConRegionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpConRegionalLayout = new javax.swing.GroupLayout(jpConRegional);
        jpConRegional.setLayout(jpConRegionalLayout);
        jpConRegionalLayout.setHorizontalGroup(
            jpConRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConRegionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConRegionalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrarConRegional))
                    .addGroup(jpConRegionalLayout.createSequentialGroup()
                        .addGroup(jpConRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btnEditarConRegional)
                            .addGroup(jpConRegionalLayout.createSequentialGroup()
                                .addComponent(lblConselho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNovoConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpConRegionalLayout.setVerticalGroup(
            jpConRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConRegionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpConRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConselho)
                    .addComponent(txtNovoConselho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarConRegional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarConRegional)
                .addContainerGap())
        );

        jtpCabecalho.addTab("Conselho Regional", jpConRegional);

        jLabel1.setText("GERENCIAR ESPECIALIZAÇÕES");

        lblEspecialidade.setText("Nova especialização:");

        btnCadastrarEsp.setText("CADASTRAR");
        btnCadastrarEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEspActionPerformed(evt);
            }
        });

        jlEspecializacoes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlEspecializacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEspecializacoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlEspecializacoes);

        btnEditarEsp.setText("EDITAR");
        btnEditarEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEspecialidadesLayout = new javax.swing.GroupLayout(jpEspecialidades);
        jpEspecialidades.setLayout(jpEspecialidadesLayout);
        jpEspecialidadesLayout.setHorizontalGroup(
            jpEspecialidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEspecialidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEspecialidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEspecialidadesLayout.createSequentialGroup()
                        .addComponent(lblEspecialidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrarEsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(jpEspecialidadesLayout.createSequentialGroup()
                        .addGroup(jpEspecialidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnEditarEsp))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpEspecialidadesLayout.setVerticalGroup(
            jpEspecialidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEspecialidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEspecialidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidade)
                    .addComponent(txtNomeEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarEsp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarEsp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpCabecalho.addTab("Especializações", jpEspecialidades);

        jLabel2.setText("GERENCIAR FORMAS DE PAGAMENTO");

        btnEditarForPag.setText("EDITAR");
        btnEditarForPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarForPagActionPerformed(evt);
            }
        });

        lblForma.setText("Nova forma:");

        jlFormas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlFormas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlFormasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jlFormas);

        btnCadastrarForPag.setText("CADASTRAR");
        btnCadastrarForPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarForPagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpForPagamentoLayout = new javax.swing.GroupLayout(jpForPagamento);
        jpForPagamento.setLayout(jpForPagamentoLayout);
        jpForPagamentoLayout.setHorizontalGroup(
            jpForPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpForPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpForPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpForPagamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrarForPag))
                    .addGroup(jpForPagamentoLayout.createSequentialGroup()
                        .addGroup(jpForPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnEditarForPag)
                            .addGroup(jpForPagamentoLayout.createSequentialGroup()
                                .addComponent(lblForma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeForma, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpForPagamentoLayout.setVerticalGroup(
            jpForPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpForPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpForPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForma)
                    .addComponent(txtNomeForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarForPag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarForPag)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpCabecalho.addTab("Formas de pagamento", jpForPagamento);

        jLabel3.setText("GERENCIAR HORÁRIOS DOS PROFISSIONAIS REALIZANTES");

        lblProfissional.setText("Profissional:");

        jlProfissionais.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlProfissionais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlProfissionaisMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jlProfissionais);

        btnCadastrarHorario.setText("CADASTRAR");
        btnCadastrarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarHorarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Horários:");

        jlHoras.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlHoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlHorasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jlHoras);

        jLabel6.setText("Novo horário:");

        try {
            txtNovaHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnExcluirHorario.setText("EXCLUIR");
        btnExcluirHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHorProfissionaisLayout = new javax.swing.GroupLayout(jpHorProfissionais);
        jpHorProfissionais.setLayout(jpHorProfissionaisLayout);
        jpHorProfissionaisLayout.setHorizontalGroup(
            jpHorProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHorProfissionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpHorProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHorProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProfissional)
                        .addComponent(jScrollPane3))
                    .addGroup(jpHorProfissionaisLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNovaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpHorProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHorProfissionaisLayout.createSequentialGroup()
                        .addComponent(btnCadastrarHorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirHorario))
                    .addGroup(jpHorProfissionaisLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jpHorProfissionaisLayout.setVerticalGroup(
            jpHorProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHorProfissionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpHorProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfissional)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpHorProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpHorProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNovaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarHorario)
                    .addComponent(btnExcluirHorario))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jtpCabecalho.addTab("Horários dos profissionais", jpHorProfissionais);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpCabecalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpCabecalho)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarHorarioActionPerformed
        // TODO add your handling code here:
        if (!txtNovaHora.getText().equalsIgnoreCase("  :  ") || jlProfissionais.getSelectedIndex() != -1) {
            HorarioAgendaController.createNovoHorario(pro.getPessoaCodigo(), txtNovaHora.getText());
            redefHoras(pro.getPessoaCodigo());
        } else {
            JOptionPane.showMessageDialog(null, "Um profissional deve ser selecionado e um horário válido deve ser informado.");
        }
    }//GEN-LAST:event_btnCadastrarHorarioActionPerformed

    private void jlProfissionaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlProfissionaisMouseClicked
        // TODO add your handling code here:
        Object[] value = jlProfissionais.getSelectedValues();
        pro = (ProfissionalBean) value[0];
        if (jlProfissionais.getSelectedIndex() != -1) {
            redefHoras(pro.getPessoaCodigo());
        }
    }//GEN-LAST:event_jlProfissionaisMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        defListPro();
        redefHoras(0);
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnExcluirHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirHorarioActionPerformed
        // TODO add your handling code here:
        if (jlProfissionais.getSelectedIndex() != -1 && jlHoras.getSelectedIndex() != -1) {
            HorarioAgendaController.deleteHorario(pro.getPessoaCodigo(), horario);
            redefHoras(pro.getPessoaCodigo());
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um horario para excluir.");
        }
    }//GEN-LAST:event_btnExcluirHorarioActionPerformed

    private void jlHorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHorasMouseClicked
        // TODO add your handling code here:
        Object[] value = jlHoras.getSelectedValues();
        horario = (String) value[0];
    }//GEN-LAST:event_jlHorasMouseClicked

    private void btnCadastrarEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEspActionPerformed
        // TODO add your handling code here:
        if(!txtNomeEspecializacao.getText().equalsIgnoreCase("")){
            EspecializacaoController.createEspecializacao(txtNomeEspecializacao.getText());
            defListas();
        } else {
            JOptionPane.showMessageDialog(null, "Informe o nome da especialização.");
        }
    }//GEN-LAST:event_btnCadastrarEspActionPerformed

    private void btnEditarEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEspActionPerformed
        // TODO add your handling code here:
        if(jlEspecializacoes.getSelectedIndex() != -1){
            EditarEspecializacaoView editar = new EditarEspecializacaoView(this, rootPaneCheckingEnabled, especializacao);
            editar.setVisible(true);
            defListas();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma especialização para editar.");
        }
    }//GEN-LAST:event_btnEditarEspActionPerformed

    private void jlEspecializacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEspecializacoesMouseClicked
        // TODO add your handling code here:
        Object[] value = jlEspecializacoes.getSelectedValues();
        especializacao = ((EspecializacaoBean)value[0]).getDescricao();
    }//GEN-LAST:event_jlEspecializacoesMouseClicked

    private void btnCadastrarConRegionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarConRegionalActionPerformed
        // TODO add your handling code here:
        if(!txtNovoConselho.getText().equalsIgnoreCase("")){
            ConselhoRegionalController.createConRegional(txtNovoConselho.getText());
            defListas();
        } else {
            JOptionPane.showMessageDialog(null, "Informe um conselho regional para cadastrar.");
        }
    }//GEN-LAST:event_btnCadastrarConRegionalActionPerformed

    private void jlConRegionaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConRegionaisMouseClicked
        // TODO add your handling code here:
        Object[] value = jlConRegionais.getSelectedValues();
        conselhoregional = ((ConselhoRegionalBean)value[0]).getDescricao();
    }//GEN-LAST:event_jlConRegionaisMouseClicked

    private void btnEditarConRegionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarConRegionalActionPerformed
        // TODO add your handling code here:
        if(jlConRegionais.getSelectedIndex() != -1){
            EditarConRegionalView editar = new EditarConRegionalView(this, rootPaneCheckingEnabled, conselhoregional);
            editar.setVisible(true);
            defListas();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um conselho regional para editar.");
        }
    }//GEN-LAST:event_btnEditarConRegionalActionPerformed

    private void btnCadastrarForPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarForPagActionPerformed
        // TODO add your handling code here:
        if(!txtNomeForma.getText().equalsIgnoreCase("")){
            FormaPagamentoController.createFormaPagamento(txtNomeForma.getText());
            defListas();
        } else {
            JOptionPane.showMessageDialog(null, "Informe uma forma de pagamento para cadastrar.");
        }
    }//GEN-LAST:event_btnCadastrarForPagActionPerformed

    private void btnEditarForPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarForPagActionPerformed
        // TODO add your handling code here:
        if(jlFormas.getSelectedIndex() != -1){
            EditarFormaPagamentoView editar = new EditarFormaPagamentoView(this, rootPaneCheckingEnabled, formapagamento);
            editar.setVisible(true);
            defListas();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma forma de pagamento para editar.");
        }
    }//GEN-LAST:event_btnEditarForPagActionPerformed

    private void jlFormasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFormasMouseClicked
        // TODO add your handling code here:
        Object[] value = jlFormas.getSelectedValues();
        formapagamento = ((FormaPagamentoBean)value[0]).getDescricao();
    }//GEN-LAST:event_jlFormasMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracoesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarConRegional;
    private javax.swing.JButton btnCadastrarEsp;
    private javax.swing.JButton btnCadastrarForPag;
    private javax.swing.JButton btnCadastrarHorario;
    private javax.swing.JButton btnEditarConRegional;
    private javax.swing.JButton btnEditarEsp;
    private javax.swing.JButton btnEditarForPag;
    private javax.swing.JButton btnExcluirHorario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> jlConRegionais;
    private javax.swing.JList<String> jlEspecializacoes;
    private javax.swing.JList<String> jlFormas;
    private javax.swing.JList<String> jlHoras;
    private javax.swing.JList<String> jlProfissionais;
    private javax.swing.JPanel jpConRegional;
    private javax.swing.JPanel jpEspecialidades;
    private javax.swing.JPanel jpForPagamento;
    private javax.swing.JPanel jpHorProfissionais;
    private javax.swing.JTabbedPane jtpCabecalho;
    private javax.swing.JLabel lblConselho;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblForma;
    private javax.swing.JLabel lblProfissional;
    private javax.swing.JTextField txtNomeEspecializacao;
    private javax.swing.JTextField txtNomeForma;
    private javax.swing.JFormattedTextField txtNovaHora;
    private javax.swing.JTextField txtNovoConselho;
    // End of variables declaration//GEN-END:variables
}
