/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.funcionario;

import model.bean.CargoBean;
import model.bean.ConselhoRegionalBean;
import model.bean.EspecializacaoBean;
import model.bean.ProfissionalBean;
import controller.FuncionarioController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.combobox.CargoComboBoxModel;
import model.combobox.ConselhoComboBoxModel;
import model.combobox.EspecializacaoComboBoxModel;
import util.GerViewUtil;

/**
 *
 * @author vande
 */
public class CadastrarFuncionarioView extends javax.swing.JDialog {

    private final CargoComboBoxModel cargocomboboxmodel = new CargoComboBoxModel();
    private final ConselhoComboBoxModel conselhocomboboxmodel = new ConselhoComboBoxModel();
    private final EspecializacaoComboBoxModel especializacaocomboboxmodel = new EspecializacaoComboBoxModel();

    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarFuncionarioView(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jcbCargo.setModel(cargocomboboxmodel);
        jcbConselho.setModel(conselhocomboboxmodel);
        jcbEspecializacao.setModel(especializacaocomboboxmodel);
        blockFormMedRealizante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jpCadUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrbFem = new javax.swing.JRadioButton();
        jrbMas = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jcbCargo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jcbConselho = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtNumConselho = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jcbEspecializacao = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jcbUf = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cila's System - Cadastrar novo funcionário(a)");
        setResizable(false);

        jLabel1.setText("Nome completo:");

        jLabel2.setText("Data de nascimento:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("CADASTRAR FUNCIONÁRIO(A)");

        jLabel4.setText("Gênero:");

        buttonGroup1.add(jrbFem);
        jrbFem.setText("Feminino");

        buttonGroup1.add(jrbMas);
        jrbMas.setText("Masculino");

        jLabel6.setText("Cargo:");

        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCargoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Login:");

        jLabel8.setText("Senha:");

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setText("CADASTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Conselho:");

        jcbConselho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Nº conselho:");

        jLabel11.setText("Especialização:");

        jcbEspecializacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("UF:");

        jcbUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"AC", "AL", "AP", "AM",
            "BA", "CE", "DF", "ES",
            "GO", "MA", "MT", "MS",
            "MG", "PA", "PB", "PR",
            "PE", "PI", "RJ", "RN",
            "RS", "RO", "RR", "SC",
            "SP", "SE", "TO"}));

javax.swing.GroupLayout jpCadUsuarioLayout = new javax.swing.GroupLayout(jpCadUsuario);
jpCadUsuario.setLayout(jpCadUsuarioLayout);
jpCadUsuarioLayout.setHorizontalGroup(
    jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jpCadUsuarioLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadUsuarioLayout.createSequentialGroup()
                .addComponent(jcbConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNumConselho)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jcbEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)))
            .addComponent(jLabel3)
            .addComponent(jButton1)
            .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpCadUsuarioLayout.createSequentialGroup()
                    .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpCadUsuarioLayout.createSequentialGroup()
                                .addComponent(jcbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLogin))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCadUsuarioLayout.createSequentialGroup()
                                .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpCadUsuarioLayout.createSequentialGroup()
                            .addComponent(jrbFem)
                            .addGap(4, 4, 4)
                            .addComponent(jrbMas))
                        .addComponent(jLabel8)
                        .addComponent(txtSenha)
                        .addGroup(jpCadUsuarioLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel4)))))
            .addComponent(jLabel9))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jpCadUsuarioLayout.setVerticalGroup(
        jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jpCadUsuarioLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jrbFem)
                .addComponent(jrbMas))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jLabel7)
                .addComponent(jLabel8))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jcbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(jLabel10)
                .addComponent(jLabel11)
                .addComponent(jLabel12))
            .addGap(5, 5, 5)
            .addGroup(jpCadUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jcbConselho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtNumConselho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jcbEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jmSobre.setText("Sobre");
    jMenuBar1.add(jmSobre);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jpCadUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jpCadUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (checkForm()) {
            ProfissionalBean pro = new ProfissionalBean();
            pro.setNome(txtNome.getText());
            try {
                Date dataNas = new SimpleDateFormat("dd/MM/yyyy").parse(txtDataNascimento.getText());
                pro.setDataNascimento(dataNas);
            } catch (ParseException ex) {
                Logger.getLogger(CadastrarFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (jrbFem.isSelected()) {
                pro.setSexo("F");
            }
            if (jrbMas.isSelected()) {
                pro.setSexo("M");
            }
            pro.setCargo(new CargoBean(jcbCargo.getSelectedItem().toString()));
            pro.setLogin(txtLogin.getText());
            pro.setSenha(new String(txtSenha.getPassword()));
            if (jcbCargo.getSelectedItem().toString().equals("Profissional realizante")) {
                pro.setConselho(new ConselhoRegionalBean(jcbConselho.getSelectedItem().toString()));
                pro.setNumConselho(Integer.parseInt(txtNumConselho.getText()));
                pro.setEspecializacao(new EspecializacaoBean(jcbEspecializacao.getSelectedItem().toString()));
                pro.setUfConselho(jcbUf.getSelectedItem().toString());
            }
            FuncionarioController.createFuncionario(pro);
            this.setVisible(false);
            if(!GerViewUtil.checkIfGerFunOpen()){
                System.exit(1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os dados");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCargoItemStateChanged
        // TODO add your handling code here:
        checkFormMedRealizante();
    }//GEN-LAST:event_jcbCargoItemStateChanged

    /**
     * Liberar ou bloquear parte do formulário para Profissional realizante conforme
     * mudança de seleção.
     */
    private void checkFormMedRealizante() {
        if (jcbCargo.getSelectedItem().toString().equals("Profissional realizante")) {
            unblockFormMedRealizante();
        } else {
            blockFormMedRealizante();
        }
    }

    /**
     * Bloquear parte do formulário para Profissional realizante
     */
    private void blockFormMedRealizante() {
        jcbConselho.setEnabled(false);
        txtNumConselho.setEnabled(false);
        jcbEspecializacao.setEnabled(false);
        jcbUf.setEnabled(false);
    }

    /**
     * Liberar parte do formulário para Profissional realizante
     */
    private void unblockFormMedRealizante() {
        jcbConselho.setEnabled(true);
        txtNumConselho.setEnabled(true);
        jcbEspecializacao.setEnabled(true);
        jcbUf.setEnabled(true);
    }

    /**
     * Método para válidar o preenchimento do formulário.
     *
     * @return
     */
    private boolean checkForm() {
        if (txtNome.getText().isEmpty()) {
            return false;
        }
        if (txtDataNascimento.getText().equalsIgnoreCase("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Data de nascimento inválida!");
            return false;
        }
        if (!jrbFem.isSelected() && !jrbMas.isSelected()) {
            return false;
        }
        if (txtLogin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o login.");
            return false;
        }
        if (txtSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe uma senha.");
            return false;
        }
        if (jcbCargo.getSelectedItem().toString().equals("Profissional realizante.")) {
            if (jcbConselho.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um conselho.");
                return false;
            }
            if (txtNumConselho.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Informe o número do conselho.");
                return false;
            }
            if (jcbEspecializacao.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione uma especialização.");
                return false;
            }
            if (jcbUf.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione a UF do conselho.");
                return false;
            }
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarFuncionarioView dialog = new CadastrarFuncionarioView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JComboBox<String> jcbConselho;
    private javax.swing.JComboBox<String> jcbEspecializacao;
    private javax.swing.JComboBox<String> jcbUf;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JPanel jpCadUsuario;
    private javax.swing.JRadioButton jrbFem;
    private javax.swing.JRadioButton jrbMas;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumConselho;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
