/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.funcionario;

import model.bean.ConselhoRegionalBean;
import model.bean.EspecializacaoBean;
import model.bean.ProfissionalBean;
import controller.FuncionarioController;
import controller.ProfissionalController;
import javax.swing.JOptionPane;
import model.combobox.ConselhoComboBoxModel;
import model.combobox.EspecializacaoComboBoxModel;

/**
 *
 * @author vande
 */
public class CadastrarFunProRealizanteView extends javax.swing.JDialog {

    private static ConselhoComboBoxModel comboboxmodelConselho = new ConselhoComboBoxModel();
    private static EspecializacaoComboBoxModel comboboxmodelEspecializacao = new EspecializacaoComboBoxModel();
    private static ProfissionalBean pro = new ProfissionalBean();

    /**
     * Creates new form EditarFunProRealizante
     */
    public CadastrarFunProRealizanteView(javax.swing.JDialog parent, boolean modal, ProfissionalBean pro) {
        super(parent, modal);
        initComponents();
        System.out.println("Código pessoa: "+pro.getPessoaCodigo());
        this.pro = pro;
        jcbConselhoRegional.setModel(comboboxmodelConselho);
        jcbEspecializacao.setModel(comboboxmodelEspecializacao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCadProfissional = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbConselhoRegional = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNumConselho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbUf = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcbEspecializacao = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cila's System - Inserir profissional realizante");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("EDITAR PROFISSIONAL");

        jLabel3.setText("Conselho:");

        jcbConselhoRegional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Nº do conselho:");

        jLabel5.setText("UF:");

        jcbUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"AC", "AL", "AP", "AM",
            "BA", "CE", "DF", "ES",
            "GO", "MA", "MT", "MS",
            "MG", "PA", "PB", "PR",
            "PE", "PI", "RJ", "RN",
            "RS", "RO", "RR", "SC",
            "SP", "SE", "TO"}));

jLabel6.setText("Especialização:");

jcbEspecializacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

btnSalvar.setText("SALVAR");
btnSalvar.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalvarActionPerformed(evt);
    }
    });

    javax.swing.GroupLayout jpCadProfissionalLayout = new javax.swing.GroupLayout(jpCadProfissional);
    jpCadProfissional.setLayout(jpCadProfissionalLayout);
    jpCadProfissionalLayout.setHorizontalGroup(
        jpCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jpCadProfissionalLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jpCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel1)
                .addComponent(jLabel6)
                .addComponent(btnSalvar)
                .addGroup(jpCadProfissionalLayout.createSequentialGroup()
                    .addGroup(jpCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jcbConselhoRegional, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpCadProfissionalLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel5))
                        .addGroup(jpCadProfissionalLayout.createSequentialGroup()
                            .addComponent(txtNumConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jcbEspecializacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jpCadProfissionalLayout.setVerticalGroup(
        jpCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jpCadProfissionalLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jLabel4)
                .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jcbConselhoRegional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtNumConselho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jcbEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnSalvar)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jpCadProfissional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jpCadProfissional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (checkForm()) {
            pro.setConselho(new ConselhoRegionalBean(jcbConselhoRegional.getSelectedItem().toString()));
            pro.setNumConselho(Integer.parseInt(txtNumConselho.getText()));
            pro.setUfConselho((String) jcbUf.getSelectedItem());
            pro.setEspecializacao(new EspecializacaoBean(jcbEspecializacao.getSelectedItem().toString()));
            ProfissionalController.createProfissionalRealizante(pro);
            FuncionarioController.updateFuncionario(pro);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * Checa os dados preenchidos no formulário de cadastro de profissional.
     */
    private boolean checkForm() {
        if (jcbConselhoRegional.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Conselho deve ser selecionado.");
            return false;
        }

        if (txtNumConselho.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Número do conselho é obrigatório");
            return false;
        }
        if (jcbUf.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "UF é obrigatório");
            return false;
        }
        if (jcbEspecializacao.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Especialização é obrigatório");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFunProRealizanteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFunProRealizanteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFunProRealizanteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFunProRealizanteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarFunProRealizanteView dialog = new CadastrarFunProRealizanteView(new javax.swing.JDialog(), true, pro);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jcbConselhoRegional;
    private javax.swing.JComboBox<String> jcbEspecializacao;
    private javax.swing.JComboBox<String> jcbUf;
    private javax.swing.JPanel jpCadProfissional;
    private javax.swing.JTextField txtNumConselho;
    // End of variables declaration//GEN-END:variables
}
