/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.funcionario;

import model.bean.CargoBean;
import model.bean.ProfissionalBean;
import controller.FuncionarioController;
import dao.FuncionarioDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.jtable.FuncionarioTableModel;
import util.GerViewUtil;
import util.MaskFormatTextUtil;

/**
 *
 * @author vande
 */
public class GerenciarFuncionariosView extends javax.swing.JFrame {

    public static FuncionarioTableModel tablemodelFuncionario = null;
    private ProfissionalBean pro = null;

    /**
     * Creates new form GerenciarFuncionarios
     */
    public GerenciarFuncionariosView() {
        initComponents();
        jtFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        defPacienteTableModelBySearch();
        defColumnFuncionarioTable();
    }

    /**
     * Método que define o tamanho das colunas da tabela de funcionarios.
     */
    private void defColumnFuncionarioTable() {
        jtFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(200);
        jtFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(70);
        jtFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(80);
        jtFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(120);
    }

    /**
     * Método usado pelo listener quando digitado um valor no campo de busca de
     * pacientes, além de setar um model para tabela.
     */
    private void defPacienteTableModelBySearch() {
        tablemodelFuncionario = new FuncionarioTableModel(txtSearchFun.getText());
        jtFuncionarios.setModel(tablemodelFuncionario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchFun = new javax.swing.JTextField();
        btnCadFuncionario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFuncionarios = new javax.swing.JTable();
        btnEditarFun = new javax.swing.JButton();
        btnExcluirFun = new javax.swing.JButton();
        jmbGerFuncionario = new javax.swing.JMenuBar();
        jmSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cila's System - Gerenciar funcionários");
        setResizable(false);

        jLabel1.setText("Nome:");

        txtSearchFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFunActionPerformed(evt);
            }
        });
        txtSearchFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchFunKeyReleased(evt);
            }
        });

        btnCadFuncionario.setText("CADASTRAR NOVO");
        btnCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionarioActionPerformed(evt);
            }
        });

        jtFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFuncionarios);

        btnEditarFun.setText("EDITAR");
        btnEditarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFunActionPerformed(evt);
            }
        });

        btnExcluirFun.setText("EXCLUIR");
        btnExcluirFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFunActionPerformed(evt);
            }
        });

        jmSobre.setText("Sobre");
        jmbGerFuncionario.add(jmSobre);

        setJMenuBar(jmbGerFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchFun, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditarFun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirFun)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearchFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarFun)
                    .addComponent(btnExcluirFun))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchFunKeyReleased
        // TODO add your handling code here:
        System.gc(); //Garbage collector
        defPacienteTableModelBySearch();
        defColumnFuncionarioTable();
    }//GEN-LAST:event_txtSearchFunKeyReleased

    private void btnCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionarioActionPerformed
        // TODO add your handling code here:
        CadastrarFuncionarioView cad = new CadastrarFuncionarioView(this, true);
        cad.setVisible(true);
    }//GEN-LAST:event_btnCadFuncionarioActionPerformed

    private void btnExcluirFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFunActionPerformed
        // TODO add your handling code here:
        if (jtFuncionarios.getSelectedRowCount() != 0) {
            int confirm = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o(a) funcionário(a) " + pro.getNome() + "?");
            switch (confirm) {
                case JOptionPane.YES_OPTION:
                    FuncionarioController.deleteFuncionario(pro);
                    break;
                default:
                    break;
            }
        } else {
            pro = null;
            JOptionPane.showMessageDialog(null, "Nenhum(a) funcionário(a) selecionado(a).");
        }
    }//GEN-LAST:event_btnExcluirFunActionPerformed

    private void btnEditarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFunActionPerformed
        // TODO add your handling code here:
        if (jtFuncionarios.getSelectedRowCount() != 0) {
            EditarFuncionarioView edi = new EditarFuncionarioView(this, true, pro);
            edi.setVisible(true);
        } else {
            pro = null;
            JOptionPane.showMessageDialog(null, "Nenhum(a) funcionário(a) selecionado(a).");
        }
    }//GEN-LAST:event_btnEditarFunActionPerformed

    private void jtFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFuncionariosMouseClicked
        // TODO add your handling code here:
        pro = new ProfissionalBean();
        pro.setNome((String) jtFuncionarios.getValueAt(jtFuncionarios.getSelectedRow(), 0));
        try {
            pro.setDataNascimento(new SimpleDateFormat("dd/MM/yyyy").parse((String) jtFuncionarios.getValueAt(jtFuncionarios.getSelectedRow(), 1)));
        } catch (ParseException ex) {
            Logger.getLogger(GerenciarFuncionariosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        pro.setSexo(MaskFormatTextUtil.sexoByGenero((String) jtFuncionarios.getValueAt(jtFuncionarios.getSelectedRow(), 2)));
        pro.setLogin((String) jtFuncionarios.getValueAt(jtFuncionarios.getSelectedRow(), 3));
        pro.setCargo(new CargoBean((String) jtFuncionarios.getValueAt(jtFuncionarios.getSelectedRow(), 4)));
    }//GEN-LAST:event_jtFuncionariosMouseClicked

    private void txtSearchFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarFuncionariosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadFuncionario;
    private javax.swing.JButton btnEditarFun;
    private javax.swing.JButton btnExcluirFun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JMenuBar jmbGerFuncionario;
    private javax.swing.JTable jtFuncionarios;
    private javax.swing.JTextField txtSearchFun;
    // End of variables declaration//GEN-END:variables
}
