/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.convenio;

import model.bean.CepBean;
import model.bean.ConsultaPorConvenioBean;
import model.bean.ConvenioBean;
import controller.ConsultaController;
import controller.ConsultaPorConvenioController;
import controller.ConvenioController;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.jtable.ConsultaPorConvenioTableModel;
import util.MaskFormatTextUtil;
import util.WebServicesUtil;
import view.consulta.AdicionarConsultaView;

/**
 *
 * @author vande
 */
public class EditarConvenioView extends javax.swing.JDialog {

    private ConsultaPorConvenioBean conBycon = null;
    private static ConvenioBean conv = null;
    private CepBean cep = null;
    public static ConsultaPorConvenioTableModel tablemodelConPorCon = null;

    /**
     * Criar novo form CadastrarConvenio e setar dados no formulário.
     *
     * @param conv
     */
    public EditarConvenioView(java.awt.Frame parent, boolean modal, ConvenioBean conv) {
        super(parent, modal);
        initComponents();
        this.conv = ConvenioController.searchConvenioByCnpj(conv);
        checkCon();
        presetConvenio();
        defConsultaPorCOnvenioTable();
        jtConPorCon.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        defColumnFuncionarioTable();
    }

    /**
     * Método usado para quando digitado um valor no campo de busca de
     * consultas, além de setar um model para tabela.
     */
    private void defConsultaPorCOnvenioTable() {
        tablemodelConPorCon = new ConsultaPorConvenioTableModel(conv.getNome());
        jtConPorCon.setModel(tablemodelConPorCon);
    }

    /**
     * Método que define o tamanho das colunas da tabela de convênios.
     */
    private void defColumnFuncionarioTable() {
        jtConPorCon.getColumnModel().getColumn(0).setPreferredWidth(400);
        jtConPorCon.getColumnModel().getColumn(1).setPreferredWidth(100);
    }

    /**
     * Preencher o formulário com dados do funcionário.
     *
     * @param conv
     */
    private void presetConvenio() {
        txtNome.setText(conv.getNome());
        txtCnpj.setText(conv.getCnpj());
        txtRazaoSocial.setText(conv.getRazaoSocial());
        txtTelefone.setText(conv.getTelefone());
        txtEmail.setText(conv.getEmail());
        txtCep.setText(conv.getCep());
        txtLogradouro.setText(conv.getLogradouro());
        txtNumResidencial.setText(conv.getNumeroResidencial());
        txtBairro.setText(conv.getBairro());
        txtCidade.setText(conv.getCidade());
        jcbUf.setSelectedItem(conv.getUf());
        conBycon = new ConsultaPorConvenioBean();
        conBycon.setConvenio(new ConvenioBean(conv.getConvenioCodigo()));
    }

    /**
     * Checar se conv é nulo. Se for a janela será fechada.
     */
    private void checkCon() {
        if (conv == null) {
            JOptionPane.showMessageDialog(null, "Nenhum convênio selecionado anteriormente.");
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmCadConvenio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        txtNumResidencial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jcbUf = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConPorCon = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        btnAddConsulta = new javax.swing.JButton();
        btnExcluirConsulta = new javax.swing.JButton();
        btnEdiConsulta = new javax.swing.JButton();
        txtCnpj = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCep = new javax.swing.JFormattedTextField();
        jmbCadConvenio = new javax.swing.JMenuBar();
        jmSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cila's System - Editar convênio");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("EDITAR CONVÊNIO");

        jLabel2.setText("Nome:");

        jLabel3.setText("CNPJ:");

        jLabel5.setText("Telefone:");

        jLabel4.setText("Razão social:");

        jLabel6.setText("E-mail:");

        jLabel7.setText("CEP:");

        jLabel8.setText("Logradouro:");

        jLabel9.setText("Número residencial:");

        jLabel10.setText("Bairro:");

        jcbUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"AC", "AL", "AP", "AM",
            "BA", "CE", "DF", "ES",
            "GO", "MA", "MT", "MS",
            "MG", "PA", "PB", "PR",
            "PE", "PI", "RJ", "RN",
            "RS", "RO", "RR", "SC",
            "SP", "SE", "TO"}));

jLabel11.setText("Cidade:");

jLabel12.setText("UF:");

btnSalvar.setText("SALVAR");
btnSalvar.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalvarActionPerformed(evt);
    }
    });

    jtConPorCon.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    jtConPorCon.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jtConPorConMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jtConPorCon);

    jLabel13.setText("CONSULTAS PELO CONVÊNIO:");

    btnAddConsulta.setText("ADICIONAR CONSULTA");
    btnAddConsulta.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddConsultaActionPerformed(evt);
        }
    });

    btnExcluirConsulta.setText("EXCLUIR CONSULTA");
    btnExcluirConsulta.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExcluirConsultaActionPerformed(evt);
        }
    });

    btnEdiConsulta.setText("EDITAR VALOR");
    btnEdiConsulta.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEdiConsultaActionPerformed(evt);
        }
    });

    try {
        txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####.##")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }

    try {
        txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }

    try {
        txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }
    txtCep.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtCepFocusLost(evt);
        }
    });

    javax.swing.GroupLayout jmCadConvenioLayout = new javax.swing.GroupLayout(jmCadConvenio);
    jmCadConvenio.setLayout(jmCadConvenioLayout);
    jmCadConvenioLayout.setHorizontalGroup(
        jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jmCadConvenioLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jmCadConvenioLayout.createSequentialGroup()
                    .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jmCadConvenioLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jmCadConvenioLayout.createSequentialGroup()
                            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jmCadConvenioLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(165, 165, 165))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jmCadConvenioLayout.createSequentialGroup()
                                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jmCadConvenioLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(0, 163, Short.MAX_VALUE))
                                .addComponent(txtRazaoSocial)))))
                .addComponent(jSeparator1)
                .addGroup(jmCadConvenioLayout.createSequentialGroup()
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jcbUf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jmCadConvenioLayout.createSequentialGroup()
                    .addComponent(txtTelefone)
                    .addGap(12, 12, 12)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)
                    .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCep)
                        .addGroup(jmCadConvenioLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(jmCadConvenioLayout.createSequentialGroup()
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtNumResidencial))
                .addGroup(jmCadConvenioLayout.createSequentialGroup()
                    .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jmCadConvenioLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(206, 206, 206)
                            .addComponent(jLabel11)
                            .addGap(191, 191, 191)
                            .addComponent(jLabel12))
                        .addComponent(btnSalvar)
                        .addComponent(jLabel13)
                        .addGroup(jmCadConvenioLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnExcluirConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdiConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                        .addGroup(jmCadConvenioLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(406, 406, 406)
                            .addComponent(jLabel9)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jmCadConvenioLayout.setVerticalGroup(
        jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jmCadConvenioLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(jLabel9))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtNumResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(jLabel11)
                .addComponent(jLabel12))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnSalvar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel13)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jmCadConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jmCadConvenioLayout.createSequentialGroup()
                    .addComponent(btnAddConsulta)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnEdiConsulta)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnExcluirConsulta)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jmSobre.setText("Sobre");
    jmbCadConvenio.add(jmSobre);

    setJMenuBar(jmbCadConvenio);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jmCadConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jmCadConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Listener no botão Salvar. Pega-se os dados do formulário e set em conv
     * para enviar ao control e comitar no banco de dados
     *
     * @param evt
     */
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (checkForm()) {
            conv.setNome(txtNome.getText());
            conv.setCnpj(MaskFormatTextUtil.onlyNumbers(txtCnpj.getText()));
            conv.setRazaoSocial(txtRazaoSocial.getText());
            conv.setTelefone(MaskFormatTextUtil.onlyNumbers(txtTelefone.getText()));
            conv.setEmail(txtEmail.getText());
            conv.setCep(MaskFormatTextUtil.onlyNumbers(txtCep.getText()));
            conv.setLogradouro(txtLogradouro.getText());
            conv.setNumeroResidencial(txtNumResidencial.getText());
            conv.setBairro(txtBairro.getText());
            conv.setCidade(txtCidade.getText());
            conv.setUf((String) jcbUf.getSelectedItem());
            ConvenioController.updateConvenio(conv);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAddConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddConsultaActionPerformed
        // TODO add your handling code here:
        AdicionarConsultaView addCon = new AdicionarConsultaView(this, true, conv.getConvenioCodigo());
        addCon.setVisible(true);
        defConsultaPorCOnvenioTable();
    }//GEN-LAST:event_btnAddConsultaActionPerformed

    private void btnEdiConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdiConsultaActionPerformed
        // TODO add your handling code here:
        if (jtConPorCon.getSelectedRow() != -1) {
            EditarValorConsultaView editar = new EditarValorConsultaView(this, rootPaneCheckingEnabled, conBycon);
            editar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum exame foi selecionado.");
        }
    }//GEN-LAST:event_btnEdiConsultaActionPerformed

    private void jtConPorConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtConPorConMouseClicked
        // TODO add your handling code here:
        conBycon.setValor((String) jtConPorCon.getValueAt(jtConPorCon.getSelectedRow(), 1));
        conBycon.setConsultaCodigo(ConsultaController.searchCodConvenioByDesc((String) jtConPorCon.getValueAt(jtConPorCon.getSelectedRow(), 0)));
    }//GEN-LAST:event_jtConPorConMouseClicked

    private void btnExcluirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirConsultaActionPerformed
        // TODO add your handling code here:
        if (jtConPorCon.getSelectedRow() != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esta consulta deste convênio?");
            switch (confirm) {
                case JOptionPane.YES_OPTION:
                    ConsultaPorConvenioController.deleteConsultaPorConvenio(conBycon);
                    break;
                default:
                    break;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum exame foi selecionado.");
        }
    }//GEN-LAST:event_btnExcluirConsultaActionPerformed

    private void txtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCepFocusLost
        // TODO add your handling code here:
        presetCep();
    }//GEN-LAST:event_txtCepFocusLost

    /**
     * Preencher campos de endereco com dados gerados a partir do CEP.
     */
    private void presetCep() {
        try {
            cep = WebServicesUtil.searchCepUtil(txtCep.getText());
            txtLogradouro.setText(cep.getLogradouro());
            txtBairro.setText(cep.getBairro());
            txtCidade.setText(cep.getCidade());
            jcbUf.setSelectedItem(cep.getUf());
        } catch (Exception ex) {
            resetCep();
        }
    }

    /**
     * Reseta valores dos campos de endereço do formulário.
     */
    private void resetCep() {
        txtLogradouro.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        jcbUf.setSelectedIndex(0);
    }

    /**
     * Método para válidar o preenchimento do formulário.
     *
     * @return
     */
    private boolean checkForm() {
        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo de nome não pode estar vázio.");
            return false;
        }
        if (txtCnpj.getText().length() != 18 || txtCnpj.getText().equalsIgnoreCase("  .   .   /    .  ")) {
            JOptionPane.showMessageDialog(null, "CNJP deve conter apenas 14 digitos númericos.");
            return false;
        }
        if (txtRazaoSocial.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo da razão social não pode estar vázia.");
            return false;
        }
        if (!txtEmail.getText().isEmpty()) {
            if (!MaskFormatTextUtil.checkEmail(txtEmail.getText())) {
                JOptionPane.showMessageDialog(null, "E-mail não válido.");
                return false;
            }
        }
        if (txtTelefone.getText().length() > 13 || txtTelefone.getText().equalsIgnoreCase("(  )    -    ")) {
            JOptionPane.showMessageDialog(null, "O campo de telefone deve conter 10 digitos númericos.");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarConvenioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarConvenioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarConvenioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarConvenioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarConvenioView dialog = new EditarConvenioView(new javax.swing.JFrame(), true, conv);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddConsulta;
    private javax.swing.JButton btnEdiConsulta;
    private javax.swing.JButton btnExcluirConsulta;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcbUf;
    private javax.swing.JPanel jmCadConvenio;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JMenuBar jmbCadConvenio;
    private javax.swing.JTable jtConPorCon;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumResidencial;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
