/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.laudo;

import model.bean.FaturamentoBean;
import model.bean.LaudoBean;
import model.bean.PacienteBean;
import controller.LaudoController;
import controller.PacienteController;
import javax.swing.JOptionPane;
import model.jtable.LaudoTableModel;
import model.jtable.PacienteTableModel;
import util.MaskFormatTextUtil;

/**
 *
 * @author vande
 */
public class GerenciadorLaudoView extends javax.swing.JFrame {

    private static PacienteTableModel tmPaciente = null;
    private static LaudoTableModel tmLaudo = null;
    private PacienteBean PACIENTE = new PacienteBean();
    private LaudoBean laudo = null;

    /**
     * Creates new form GerenciadorLaudo
     */
    public GerenciadorLaudoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPaciente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtLaudo = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jlAltura = new javax.swing.JLabel();
        jlPeso = new javax.swing.JLabel();
        jlTipoSanguineo = new javax.swing.JLabel();
        jlDUM = new javax.swing.JLabel();
        jlPressaoArterial = new javax.swing.JLabel();
        jlAlergia = new javax.swing.JLabel();
        jlGestacao = new javax.swing.JLabel();
        jlDeficiencia = new javax.swing.JLabel();
        jlObservacao = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtAltura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtDum = new javax.swing.JTextField();
        txtTipoSanguineo = new javax.swing.JTextField();
        txtPressaoArterial = new javax.swing.JTextField();
        txtObservacao = new javax.swing.JTextField();
        txtDeficiencia = new javax.swing.JTextField();
        txtAlergia = new javax.swing.JTextField();
        txtGestacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cila's System - Gerenciador de laudo");
        setResizable(false);

        jLabel1.setText("GERENCIADOR DE LAUDO");

        jLabel2.setText("Pesquise pelo paciente:");

        txtPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPacienteKeyPressed(evt);
            }
        });

        jtPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPaciente);

        jLabel3.setText("Registros:");

        jtLaudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLaudoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtLaudo);

        jLabel4.setText("Dados clínicos:");

        jlAltura.setText("Altura:");

        jlPeso.setText("Peso:");

        jlTipoSanguineo.setText("Tipo sanguíneo:");

        jlDUM.setText("DUM:");

        jlPressaoArterial.setText("Pressão arterial:");

        jlAlergia.setText("Alergias:");

        jlGestacao.setText("Gestações:");

        jlDeficiencia.setText("Defiências:");

        jlObservacao.setText("Observações:");

        txtAltura.setEditable(false);

        txtPeso.setEditable(false);

        txtDum.setEditable(false);

        txtTipoSanguineo.setEditable(false);

        txtPressaoArterial.setEditable(false);

        txtObservacao.setEditable(false);

        txtDeficiencia.setEditable(false);

        txtAlergia.setEditable(false);

        txtGestacao.setEditable(false);

        jLabel5.setText("(Clique 2 vezes para abrir o laudo)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlAltura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlPeso)
                                            .addComponent(jlDUM))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPeso)
                                            .addComponent(txtDum))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlPressaoArterial)
                                    .addComponent(jlTipoSanguineo)
                                    .addComponent(jlObservacao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPressaoArterial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlDeficiencia)
                                            .addComponent(jlAlergia))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAlergia, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                            .addComponent(txtDeficiencia))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlGestacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGestacao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtObservacao)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPaciente)))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAltura)
                    .addComponent(jlTipoSanguineo)
                    .addComponent(jlDeficiencia)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlGestacao)
                    .addComponent(txtDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGestacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPressaoArterial)
                    .addComponent(txtPressaoArterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAlergia)
                    .addComponent(txtAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDUM)
                    .addComponent(txtDum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlObservacao)
                    .addComponent(txtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPacienteKeyPressed
        // TODO add your handling code here:
        if (txtPaciente.getText().equalsIgnoreCase("") || txtPaciente.getText().equalsIgnoreCase(" ")) {
            tmPaciente = new PacienteTableModel("null");
            jtPaciente.setModel(tmPaciente);
        } else {
            tmPaciente = new PacienteTableModel(txtPaciente.getText());
            jtPaciente.setModel(tmPaciente);
        }
        setColumnPacienteTable();
    }//GEN-LAST:event_txtPacienteKeyPressed

    private void jtPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPacienteMouseClicked
        // TODO add your handling code here:
        if (jtPaciente.getSelectedRow() != -1) {
            PACIENTE = PacienteController.searchPacienteByCodigo((int) jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 0));
            if (PACIENTE != null) {
                setForm(PACIENTE);
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível pegar informações do paciente selecionado.");
            }
        }
    }//GEN-LAST:event_jtPacienteMouseClicked

    private void jtLaudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLaudoMouseClicked
        // TODO add your handling code here:
        int count = evt.getClickCount();
        laudo = new LaudoBean();
        laudo.setFaturamento(new FaturamentoBean());
        laudo.getFaturamento().setFaturamentoCodigo((int) jtLaudo.getValueAt(jtLaudo.getSelectedRow(), 0));
        if (count == 2) {
            laudo = LaudoController.searchLaudo(laudo);
            if (laudo != null) {
                LaudoView laudoView = new LaudoView(this, true, laudo);
                laudoView.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Erro. Não foi criado nenhum laudo a partir do faturamento do agendamneto.");
            }
        }
    }//GEN-LAST:event_jtLaudoMouseClicked

    /**
     * Método que define o tamanho das colunas da tabela de pacientes.
     */
    private void setColumnPacienteTable() {
        jtPaciente.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtPaciente.getColumnModel().getColumn(1).setPreferredWidth(200);
        jtPaciente.getColumnModel().getColumn(2).setPreferredWidth(50);
        jtPaciente.getColumnModel().getColumn(3).setPreferredWidth(50);
    }

    private void setForm(PacienteBean pac) {
        txtAltura.setText(MaskFormatTextUtil.changeDotByComma(pac.getAltura() + ""));
        txtPeso.setText(MaskFormatTextUtil.changeDotByComma(pac.getPeso() + ""));
        txtObservacao.setText(pac.getObservacao());
        txtDum.setText(MaskFormatTextUtil.dataBr(pac.getDum()));
        txtPressaoArterial.setText(pac.getPressaoArterial());
        txtGestacao.setText(pac.getGestacao());
        txtDeficiencia.setText(pac.getDeficiencia());
        txtTipoSanguineo.setText(pac.getTipoSanguineo());
        txtAlergia.setText(pac.getAlergia());
        tmLaudo = new LaudoTableModel(PACIENTE);
        jtLaudo.setModel(tmLaudo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciadorLaudoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciadorLaudoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciadorLaudoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciadorLaudoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciadorLaudoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlAlergia;
    private javax.swing.JLabel jlAltura;
    private javax.swing.JLabel jlDUM;
    private javax.swing.JLabel jlDeficiencia;
    private javax.swing.JLabel jlGestacao;
    private javax.swing.JLabel jlObservacao;
    private javax.swing.JLabel jlPeso;
    private javax.swing.JLabel jlPressaoArterial;
    private javax.swing.JLabel jlTipoSanguineo;
    private javax.swing.JTable jtLaudo;
    private javax.swing.JTable jtPaciente;
    private javax.swing.JTextField txtAlergia;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtDeficiencia;
    private javax.swing.JTextField txtDum;
    private javax.swing.JTextField txtGestacao;
    private javax.swing.JTextField txtObservacao;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPressaoArterial;
    private javax.swing.JTextField txtTipoSanguineo;
    // End of variables declaration//GEN-END:variables
}
